export const slides = [
  {
    index: 0,
    src: "https://i.ibb.co/R60NddV/IMG-6147.jpg",
    title: "Hòa chó điên",
    description: "Hòa điên hơn chó",
  },
  {
    index: 1,
    src: "https://i.ibb.co/R2mfQZK/IMG-2282.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 2,
    src: "https://i.ibb.co/gZfj3nz/IMG-2396.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 3,
    src: "https://i.ibb.co/ChHzJs0/IMG-2279.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 4,
    src: "https://i.ibb.co/sCR7bpx/IMG-2280.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 5,
    src: "https://i.ibb.co/XkK6Qbp/IMG-2281.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 6,
    src: "https://i.ibb.co/2j0PSW8/IMG-2291.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 7,
    src: "https://i.ibb.co/KFYkpLy/IMG-2298.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 8,
    src: "https://i.ibb.co/R2WvYnS/IMG-1910.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 9,
    src: "https://i.ibb.co/KbYZZGW/IMG-1951.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 10,
    src: "https://i.ibb.co/RBVZf80/IMG-5936.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 11,
    src: "https://i.ibb.co/1Qv9QgJ/IMG-5938-1.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 12,
    src: "https://i.ibb.co/1nMQ48F/IMG-5940.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 13,
    src: "https://i.ibb.co/FD8kXt1/77-E143-F5-8-F04-4-B6-C-9-FBB-4-D7518-CD8-B88.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 14,
    src: "https://i.ibb.co/FqCZRDx/IMG-1700.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 15,
    src: "https://i.ibb.co/K2Q9FBR/IMG-1703.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 16,
    src: "https://i.ibb.co/j5SR34g/IMG-1708.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 17,
    src: "https://i.ibb.co/cgt8F7p/IMG-1722.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 18,
    src: "https://i.ibb.co/qNXTjPS/IMG-1760.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 19,
    src: "https://i.ibb.co/8xJMtPj/IMG-1595.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 20,
    src: "https://i.ibb.co/GHMjXrf/IMG-5856.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 21,
    src: "https://i.ibb.co/2tYxctR/IMG-5860.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 22,
    src: "https://i.ibb.co/XLr87bx/IMG-5713.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 23,
    src: "https://i.ibb.co/M8H4Xyv/IMG-5719.jpg",
    title: "Chưa biết",
    description: "Chưa biết",
  },
  {
    index: 24,
    src: "https://i.ibb.co/pRM9vFS/IMG-0749-1.jpg",
    title: "Chưa nghĩ ra",
    description: "Chưa nghĩ ra",
  },
  {
    index: 25,
    src: "https://i.ibb.co/927y0fT/IMG-0855.jpg",
    title: "Chưa nghĩ ra",
    description: "Chưa nghĩ ra",
  },
  {
    index: 26,
    src: "https://i.ibb.co/FHY5XD0/IMG-2207.jpg",
    title: "Chưa nghĩ đc",
    description: "lorem",
  },
  {
    index: 27,
    src: "https://i.ibb.co/dWG2sY0/IMG-5847.jpg",
    title: "Hết mình vì nghệ thuật 06/07",
    description: "Chụp 100 kiểu",
  },
  {
    index: 28,
    src: "https://i.ibb.co/JHRWZJz/IMG-6106.jpg",
    title: "Quà sinh nhật Minh Hòa",
    description: "Mới cưới mới có con",
  },
  {
    index: 29,
    src: "https://i.ibb.co/H4Mpkqk/IMG-3065.jpg",
    title: "Ăn sinh nhật Minh Hòa 15/08",
    description: "Ăn sinh nhật Minh Hòa, Minh Hòa gọi vcl",
  },
  {
    index: 30,
    src: "https://i.ibb.co/tZhNmZZ/IMG-6223.jpg",
    title: "Ăn sinh nhật Hùng Cỏ 8/9",
    description: "Ăn sinh nhật Hùng Cỏ, Minh Hòa gọi vcl",
  },
  {
    index: 31,
    src: "https://i.ibb.co/SX26FCC/IMG-6362-3.jpg",
    title: "Đi xem Joker 2 như cặc 4/10",
    description:
      "Đi xem Joker về bị bắt đi mua bvs xg chụp ảnh làm trò đùa thiên hạ",
  },
];
